// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: ohlc.proto

package ohlc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OHLC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TradePair string  `protobuf:"bytes,1,opt,name=trade_pair,json=tradePair,proto3" json:"trade_pair,omitempty"`
	OpenTime  string  `protobuf:"bytes,2,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	CloseTime string  `protobuf:"bytes,3,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	Open      float64 `protobuf:"fixed64,4,opt,name=open,proto3" json:"open,omitempty"`
	High      float64 `protobuf:"fixed64,5,opt,name=high,proto3" json:"high,omitempty"`
	Low       float64 `protobuf:"fixed64,6,opt,name=low,proto3" json:"low,omitempty"`
	Close     float64 `protobuf:"fixed64,7,opt,name=close,proto3" json:"close,omitempty"`
}

func (x *OHLC) Reset() {
	*x = OHLC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ohlc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OHLC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OHLC) ProtoMessage() {}

func (x *OHLC) ProtoReflect() protoreflect.Message {
	mi := &file_ohlc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OHLC.ProtoReflect.Descriptor instead.
func (*OHLC) Descriptor() ([]byte, []int) {
	return file_ohlc_proto_rawDescGZIP(), []int{0}
}

func (x *OHLC) GetTradePair() string {
	if x != nil {
		return x.TradePair
	}
	return ""
}

func (x *OHLC) GetOpenTime() string {
	if x != nil {
		return x.OpenTime
	}
	return ""
}

func (x *OHLC) GetCloseTime() string {
	if x != nil {
		return x.CloseTime
	}
	return ""
}

func (x *OHLC) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *OHLC) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *OHLC) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *OHLC) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

type OHLCrequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TradePair string `protobuf:"bytes,1,opt,name=trade_pair,json=tradePair,proto3" json:"trade_pair,omitempty"`
}

func (x *OHLCrequest) Reset() {
	*x = OHLCrequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ohlc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OHLCrequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OHLCrequest) ProtoMessage() {}

func (x *OHLCrequest) ProtoReflect() protoreflect.Message {
	mi := &file_ohlc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OHLCrequest.ProtoReflect.Descriptor instead.
func (*OHLCrequest) Descriptor() ([]byte, []int) {
	return file_ohlc_proto_rawDescGZIP(), []int{1}
}

func (x *OHLCrequest) GetTradePair() string {
	if x != nil {
		return x.TradePair
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ohlc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_ohlc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_ohlc_proto_rawDescGZIP(), []int{2}
}

var File_ohlc_proto protoreflect.FileDescriptor

var file_ohlc_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6f, 0x68, 0x6c, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6f, 0x68,
	0x6c, 0x63, 0x22, 0xb1, 0x01, 0x0a, 0x04, 0x4f, 0x48, 0x4c, 0x43, 0x12, 0x1d, 0x0a, 0x0a, 0x74,
	0x72, 0x61, 0x64, 0x65, 0x5f, 0x70, 0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x72, 0x61, 0x64, 0x65, 0x50, 0x61, 0x69, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x70,
	0x65, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f,
	0x70, 0x65, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x73, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x6f,
	0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69,
	0x67, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x10,
	0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x77,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x22, 0x2c, 0x0a, 0x0b, 0x4f, 0x48, 0x4c, 0x43, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x70,
	0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x72, 0x61, 0x64, 0x65,
	0x50, 0x61, 0x69, 0x72, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x40, 0x0a,
	0x0b, 0x4f, 0x48, 0x4c, 0x43, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x0e,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4f, 0x48, 0x4c, 0x43, 0x44, 0x61, 0x74, 0x61, 0x12, 0x11,
	0x2e, 0x6f, 0x68, 0x6c, 0x63, 0x2e, 0x4f, 0x48, 0x4c, 0x43, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0a, 0x2e, 0x6f, 0x68, 0x6c, 0x63, 0x2e, 0x4f, 0x48, 0x4c, 0x43, 0x30, 0x01, 0x42,
	0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x62,
	0x64, 0x75, 0x6c, 0x73, 0x68, 0x61, 0x6b, 0x6f, 0x6f, 0x72, 0x30, 0x32, 0x2f, 0x6f, 0x68, 0x6c,
	0x63, 0x5f, 0x65, 0x78, 0x69, 0x6e, 0x69, 0x74, 0x79, 0x2f, 0x6f, 0x68, 0x6c, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ohlc_proto_rawDescOnce sync.Once
	file_ohlc_proto_rawDescData = file_ohlc_proto_rawDesc
)

func file_ohlc_proto_rawDescGZIP() []byte {
	file_ohlc_proto_rawDescOnce.Do(func() {
		file_ohlc_proto_rawDescData = protoimpl.X.CompressGZIP(file_ohlc_proto_rawDescData)
	})
	return file_ohlc_proto_rawDescData
}

var file_ohlc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ohlc_proto_goTypes = []any{
	(*OHLC)(nil),        // 0: ohlc.OHLC
	(*OHLCrequest)(nil), // 1: ohlc.OHLCrequest
	(*Empty)(nil),       // 2: ohlc.Empty
}
var file_ohlc_proto_depIdxs = []int32{
	1, // 0: ohlc.OHLCService.StreamOHLCData:input_type -> ohlc.OHLCrequest
	0, // 1: ohlc.OHLCService.StreamOHLCData:output_type -> ohlc.OHLC
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ohlc_proto_init() }
func file_ohlc_proto_init() {
	if File_ohlc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ohlc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*OHLC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ohlc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*OHLCrequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ohlc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ohlc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ohlc_proto_goTypes,
		DependencyIndexes: file_ohlc_proto_depIdxs,
		MessageInfos:      file_ohlc_proto_msgTypes,
	}.Build()
	File_ohlc_proto = out.File
	file_ohlc_proto_rawDesc = nil
	file_ohlc_proto_goTypes = nil
	file_ohlc_proto_depIdxs = nil
}
